// Shared application error classes (no VALUE imports → no cycles; the one import below is a type
// query, erased at compile time). The Elysia `onError` handler maps `AppError.statusCode` before
// its generic logging branch.

// The API's error catalog, as a type. `src/api/locales/en.json` holds exactly one top-level key
// (`errors`) and is generated by `bun i18n:extract` from the `// translate(...)` ledgers in
// `src/api/**`, so a key nothing registers is pruned out of it. Typed rather than checked later
// because `translateWithLocale` falls back to `message` for an unknown key: no throw, no log, just
// English for every caller, invisible at runtime.
type ApiLocale = typeof import("@/api/locales/en.json");
export type ErrorTranslationKey =
  `errors.${keyof ApiLocale["errors"] & string}`;

export class AppError extends Error {
  readonly statusCode: number;
  // NOTE: optional i18n key. When set, `onError` translates it (per the request's
  // Accept-Language) before sending the body, with `message` as the English fallback.
  // Without it, the raw `message` reaches the client (fine for protocol/internal errors
  // like OAuth `invalid_grant`, wrong for user-facing flows — set a key there).
  readonly translationKey?: ErrorTranslationKey;
  // NOTE: interpolation values for translationKey ({{placeholders}} in the locale entry).
  // `message` must arrive pre-interpolated: it is the log line and the untranslated fallback.
  readonly translationParams?: Record<string, string | number>;
  // NOTE: optional. The value this refusal is ABOUT, by the name the SERVER uses for it: a column
  // (`systemPrompt`), a key of a patch (`document`), or a dotted path into a bag the server owns
  // (`guardrails.output.templateMessage`). Never a form path and never localized: it is a key the
  // client keys on, and it must read the same in every language the sentence is written in.
  // The server's vocabulary rather than the request's, because REST and MCP spell the same
  // write differently, and the console already maps these paths (TEXT_CAP_TARGETS,
  // src/modules/agents/config-health.ts). Absent when the refusal is not about one input (see
  // src/api/lib/refusal.ts).
  readonly field?: string;
  // NOTE: optional. The playground turn this refusal ended, so the console can point at its lines on
  // the Logs page. Set by the playground's entry points on the way out rather than in the
  // constructor, since the error is usually raised far below the code that knows the turn.
  turnId?: string;
  constructor(
    message: string,
    statusCode: number,
    translationKey?: ErrorTranslationKey,
    translationParams?: Record<string, string | number>,
    field?: string,
  ) {
    super(message);
    this.name = new.target.name;
    this.statusCode = statusCode;
    this.translationKey = translationKey;
    this.translationParams = translationParams;
    this.field = field;
  }
}

export class ForbiddenError extends AppError {
  constructor(message = "Forbidden", translationKey?: ErrorTranslationKey) {
    super(message, 403, translationKey);
  }
}

// NOTE: raised when a Pro-only mutation is reached in the Free edition. 403 with a user-facing i18n
// key so the client can surface an upgrade prompt. Thrown by the Free-edition paired stubs that stand
// in for Pro-only write modules (e.g. the tenants/branding admin services). Kept here (not in
// edition.ts) so this module stays import-cycle-free.
export class ProEditionError extends AppError {
  constructor(message = "This feature requires the Pro edition") {
    super(message, 403, "errors.proEdition");
  }
}

// NOTE: a uniqueness/state conflict surfaced to the user (e.g. a duplicate tenant slug).
export class ConflictError extends AppError {
  constructor(
    message = "Conflict",
    translationKey?: ErrorTranslationKey,
    field?: string,
  ) {
    super(message, 409, translationKey, undefined, field);
  }
}

// A tenant-scoped operation was attempted without a resolved target tenant (e.g. a SUPER_ADMIN call
// missing the X-Tenant-Id selector). 400, not 500. The key is set HERE because no call site passes
// a message either: the refusal is the class.
export class TenantTargetRequiredError extends AppError {
  // NOTE: the default is the catalog sentence VERBATIM, the same string as the admin surface's
  // `translate` default, so every producer of this refusal says one thing.
  constructor(message = "A target tenant is required") {
    super(message, 400, "errors.tenantTargetRequired");
  }
}

export class NotFoundError extends AppError {
  constructor(message = "Not found", translationKey?: ErrorTranslationKey) {
    super(message, 404, translationKey);
  }
}

// The tenant the request was AMBIENTLY scoped to is gone: the SUPER_ADMIN selector it carried (the
// console's stored `X-Tenant-Id`) names a tenant that no longer exists. Same status, key and sentence
// as the 404 for a tenant the caller NAMED, but only this one obliges the browser to drop the
// selection, so the rejected id travels to the wire (src/api/lib/refusal.ts).
export class ActiveTenantNotFoundError extends NotFoundError {
  readonly rejectedTenantId: string;
  constructor(tenantId: bigint | string) {
    super("Tenant not found", "errors.tenantNotFound");
    this.rejectedTenantId = String(tenantId);
  }
}

// The tenant selector a MEMBER sent (`X-Tenant-Id`) names a tenant they do not belong to. Refused,
// never swapped for another membership, because silently landing in the wrong tenant is the failure to prevent.
// It carries the rejected id so the console drops the selection and reloads, like
// `ActiveTenantNotFoundError` (src/api/lib/refusal.ts). A nonexistent tenant gets this same answer,
// so the refusal says nothing about which ids exist.
export class TenantSelectorRefusedError extends ForbiddenError {
  readonly rejectedTenantId: string;
  constructor(tenantId: string) {
    super("Forbidden", "errors.forbidden");
    this.rejectedTenantId = tenantId;
  }
}

// NOTE: uniform 401 for the inbound receptor. An unknown/disabled route token and a bad
// auth signature must look identical (same status, same body) so the response never reveals
// which token strings are live.
export class UnauthorizedError extends AppError {
  constructor(message = "Unauthorized") {
    super(message, 401, "errors.unauthorized");
  }
}

// NOTE: a transient infrastructure failure surfaced while verifying the session (e.g. the
// DB pool reconnecting during a dev hot-reload, a brief outage). 503 tells the client to
// retry instead of treating the request as a logout — a null user from a swallowed DB error
// is indistinguishable from a real "no session" and would bounce the operator to /login on
// every server blip. No translationKey: the body is never user-facing (the client retries).
export class ServiceUnavailableError extends AppError {
  constructor(message = "Service temporarily unavailable") {
    super(message, 503);
  }
}
