// WHAT CHATWOOT ITSELF WRITES WHEN A LABEL CHANGES (issue #642, review round 5).
//
// An activity row carries no structure for this: no sender, and `content_attributes` only on the
// activities that declare a type (a status change), never on a label change. So the only way to know
// that a row narrates a label change is the sentence, and the only way to read a sentence without
// guessing is the TEMPLATE it was rendered from — `conversations.activity.labels.added` and
// `.removed`, interpolated with the actor's name and with `labels.join(", ")`
// (`LabelActivityMessageHandler#create_label_change_activity`).
//
// Guessing at the POSITION instead is what the two rounds before this one kept paying for: "a run of
// known titles at the edge of the line" misses German and Turkish, which put the run in the middle
// ("Hans hat vip hinzugefügt"), and the quoted form it needed for Japanese accepts any other
// activity that happens to quote a value — a priority change, a group rename. The templates say
// where the labels are in every locale, and say it exactly.
//
// COPIED FROM THE FORK, `config/locales/*.yml` of fazer-ai/chatwoot, on 14/set/2026: 74 distinct
// strings across every locale it ships, as YAML DECODES them and not as the file spells them — a
// single-quoted scalar escapes an apostrophe by doubling it, and a pattern built from the raw
// spelling waits for two apostrophes Chatwoot never writes (round 10). A template that drifts stops matching, and a line nobody
// matches is simply not read — the same miss this block already chooses over inventing a decision,
// and never a false positive.
const LABEL_ACTIVITY_TEMPLATES: readonly string[] = [
  "%{user_name} %{labels} যোগ করেছেন",
  "%{user_name} %{labels} সরিয়ে দিয়েছেন",
  "%{user_name} a ajouté %{labels}",
  "%{user_name} a következő cimkéket adta hozzá: %{labels}",
  "%{user_name} a supprimé %{labels}",
  "%{user_name} acrescentou %{labels}",
  "%{user_name} added %{labels}",
  "%{user_name} adicionou %{labels}",
  "%{user_name} adăugat %{labels}",
  "%{user_name} agregó %{labels}",
  "%{user_name} dodal %{labels}",
  "%{user_name} dodał/a %{labels}",
  "%{user_name} eliminat %{labels}",
  "%{user_name} eliminó a %{labels}",
  "%{user_name} fjernede %{labels}",
  "%{user_name} fjernet %{labels}",
  "%{user_name} ha afegit %{labels}",
  "%{user_name} ha aggiunto %{labels}",
  "%{user_name} ha eliminat %{labels}",
  "%{user_name} ha rimosso %{labels}",
  "%{user_name} har lagt till %{labels}",
  "%{user_name} hat %{labels} entfernt",
  "%{user_name} hat %{labels} hinzugefügt",
  "%{user_name} je dodao %{labels}",
  "%{user_name} je uklonio %{labels}",
  "%{user_name} la til %{labels}",
  "%{user_name} leszedte a következő cimkéket %{labels}",
  "%{user_name} lisäsi tunnisteet %{labels}",
  "%{user_name} menambahkan %{labels}",
  "%{user_name} menghapus %{labels}",
  "%{user_name} noņēma %{labels}",
  "%{user_name} odebral/a %{labels}",
  "%{user_name} odobral %{labels}",
  "%{user_name} odstranil %{labels}",
  "%{user_name} odstranil/a %{labels}",
  "%{user_name} pašalino %{labels}",
  "%{user_name} pievienoja %{labels}",
  "%{user_name} poisti tunnisteet %{labels}",
  "%{user_name} pridal %{labels}",
  "%{user_name} pridėjo %{labels}",
  "%{user_name} removed %{labels}",
  "%{user_name} removeu %{labels}",
  "%{user_name} removeu a %{labels}",
  "%{user_name} thêm %{labels}",
  "%{user_name} tilføjede %{labels}",
  "%{user_name} tog bort %{labels}",
  "%{user_name} usunął/a %{labels}",
  "%{user_name} xoá %{labels}",
  "%{user_name} видалив %{labels}",
  "%{user_name} добавил %{labels}",
  "%{user_name} додав %{labels}",
  "%{user_name} удалил %{labels}",
  "%{user_name} הוסיף %{labels}",
  "%{user_name} הסיר %{labels}",
  "%{user_name} أزال %{labels}",
  "%{user_name} أضاف %{labels}",
  "%{user_name} ले %{labels} थपे",
  "%{user_name} ले %{labels} हटाए",
  '%{user_name} がラベル "%{labels}" を削除しました',
  '%{user_name} がラベル "%{labels}" を追加しました',
  "%{user_name} 新增了 %{labels}",
  "%{user_name} 添加 %{labels}",
  "%{user_name} 移除 %{labels}",
  "%{user_name} 移除了 %{labels}",
  "%{user_name}, %{labels} ekledi",
  "%{user_name}, %{labels} kaldırdı",
  "%{user_name}، %{labels} را اضافه کرد",
  "%{user_name}، %{labels} را حذف کرد",
  "%{user_name}님이 %{labels}을(를) 제거했습니다",
  "%{user_name}님이 %{labels}을(를) 추가했습니다",
  "Idinagdag ni %{user_name} ang %{labels}",
  "Tinanggal ni %{user_name} ang %{labels}",
  "Ο %{user_name} αφαίρεσε τις ετικέτες %{labels}",
  "Ο %{user_name} πρόσθεσε ετικέτες %{labels}",
];

// EVERY OTHER ACTIVITY SENTENCE CHATWOOT CAN WRITE (round 9), all 760 of them across every locale
// and every section but `labels`: assignments, teams, priorities, SLA policies, mutes, Linear
// events, WhatsApp group updates. A line one of these explains is not a label change, whatever it
// names — asked FIRST, before any label template is tried.
//
// It started as the 58 that collide when their own placeholders hold ORDINARY values ("Ana added
// SLA policy Gold" reads as a label on an account that has one), and that was not enough, because
// the placeholder is where somebody ELSE's text goes: an agent display name of "John added vip"
// renders "Assigned to Gi by John added vip", which the English label template parses as the label
// `vip`, and a WhatsApp group name reaches a template the same way. Every rendering matches its OWN
// template, so holding all of them is what makes that class closed.
//
// The drift cuts the other way here, and it is the one thing to know when upgrading the fork: a
// label template that drifts stops matching and the line is missed, while an activity template we
// do NOT have is a sentence nothing refuses, and a crafted value inside it can be read as a change.
// Regenerate this file from `config/locales/*.yml` when the fork's activity strings move.
const OTHER_ACTIVITY_TEMPLATES: readonly string[] = [
  "%{assignee_name} %{user_name}-നെ നിയുക്തനാക്കി ",
  "%{author_name} activó la aprobación del administrador para unirse a este grupo",
  "%{author_name} alterou a descrição do grupo",
  "%{author_name} alterou a imagem do grupo",
  '%{author_name} alterou o nome do grupo para "%{value}"',
  "%{author_name} ativou a autorização de admins para entrar neste grupo",
  '%{author_name} cambió el nombre del grupo a "%{value}"',
  "%{author_name} cambió la configuración de este grupo para que solo los administradores puedan añadir a otras personas",
  "%{author_name} cambió la configuración de este grupo para que solo los administradores puedan enviar mensajes",
  "%{author_name} cambió la configuración de este grupo para que todos los miembros puedan añadir a otras personas",
  "%{author_name} cambió la configuración de este grupo para que todos los miembros puedan enviar mensajes",
  "%{author_name} cambió la configuración para que solo los administradores puedan editar la configuración del grupo",
  "%{author_name} cambió la configuración para que todos los miembros puedan editar la configuración del grupo",
  "%{author_name} cambió la descripción del grupo",
  "%{author_name} cambió la imagen del grupo",
  "%{author_name} changed the group description",
  "%{author_name} changed the group image",
  '%{author_name} changed the group name to "%{value}"',
  "%{author_name} changed the settings so all members can edit the group settings",
  "%{author_name} changed the settings so only admins can edit the group settings",
  "%{author_name} changed this group's setting to allow all members to add others to this group",
  "%{author_name} changed this group's setting to allow only admins to add others to this group",
  "%{author_name} changed this group's settings to allow all members to send messages to this group",
  "%{author_name} changed this group's settings to allow only admins to send messages to this group",
  "%{author_name} desactivó la aprobación del administrador para unirse a este grupo",
  "%{author_name} desativou a autorização de admins para entrar neste grupo",
  "%{author_name} eliminó la descripción del grupo",
  "%{author_name} mudou as configurações desse grupo para permitir que somente admins enviem mensagens ao grupo",
  "%{author_name} mudou as configurações deste grupo para permitir que somente admins adicionem outras pessoas ao grupo",
  "%{author_name} mudou as configurações do grupo para permitir que todos os membros adicionem outras pessoas",
  "%{author_name} mudou as configurações do grupo para permitir que todos os membros enviem mensagens",
  "%{author_name} mudou as configurações para permitir que somente admins editem as configurações do grupo",
  "%{author_name} mudou as configurações para permitir que todos os membros editem as configurações do grupo",
  "%{author_name} redefiniu o link do grupo para convidar outras pessoas",
  "%{author_name} removed the group description",
  "%{author_name} removeu a descrição do grupo",
  "%{author_name} reset this group's invite link",
  "%{author_name} restableció el enlace de invitación de este grupo",
  "%{author_name} turned off admin approval to join this group",
  "%{author_name} turned on admin approval to join this group",
  "%{contact_name} a accepté la demande d'autorisation d'appel.",
  "%{contact_name} accepted the call permission request.",
  "%{contact_name} aceitou a solicitação de permissão de chamada.",
  "%{contact_name} atrisināja sarunu",
  "%{contact_name} deseja entrar no grupo",
  "%{contact_name} entrou usando o link do grupo",
  "%{contact_name} ha accettato la richiesta di autorizzazione di chiamata.",
  "%{contact_name} ha aceptado la solicitud de permiso de llamada.",
  "%{contact_name} hat die Anfrage zur Anrufberechtigung angenommen.",
  "%{contact_name} joined using the group invite link",
  "%{contact_name} left the group",
  "%{contact_name} menerima permintaan izin panggilan.",
  "%{contact_name} no longer wants to join the group",
  "%{contact_name} não deseja mais fazer parte do grupo",
  "%{contact_name} quiere unirse al grupo",
  "%{contact_name} saiu do grupo",
  "%{contact_name} salió del grupo",
  "%{contact_name} se unió mediante el enlace de invitación del grupo",
  "%{contact_name} wants to join the group",
  "%{contact_name} ya no quiere unirse al grupo",
  "%{contact_name} принял запрос на разрешение звонка.",
  "%{contact_name} দ্বারা কথোপকথন সমাধান করা হয়েছে",
  "%{contact_name} によって会話が解決されました",
  "%{contact_name} 已解決此對話",
  "%{contact_name}님이 대화를 해결했습니다",
  "%{count} 日間会話が非アクティブだったため、システムにより解決済みにされました",
  "%{count}분간 비활성으로 인해 시스템이 대화를 해결됨으로 표시했습니다",
  "%{count}시간 비활성으로 인해 시스템이 대화를 해결됨으로 표시했습니다",
  "%{count}일간 비활성으로 인해 시스템이 대화를 해결됨으로 표시했습니다",
  "%{team_name} %{user_name}-നെ നിയുക്തനാക്കി ",
  "%{user_name} %{assignee_name}-কে দায়িত্ব দিয়েছেন",
  "%{user_name} SLA নীতি %{sla_name} মুছে দিয়েছেন",
  "%{user_name} SLA নীতি %{sla_name} যোগ করেছেন",
  "%{user_name} a ajouté la politique de SLA %{sla_name}",
  "%{user_name} a modifié la priorité de %{old_priority} à %{new_priority}",
  "%{user_name} a supprimé la politique de SLA %{sla_name}",
  "%{user_name} a supprimé la priorité",
  "%{user_name} added SLA policy %{sla_name}",
  "%{user_name} adicionou política de SLA %{sla_name}",
  "%{user_name} adicionou uma política de SLA %{sla_name}",
  "%{user_name} agregó la política de SLA %{sla_name}",
  "%{user_name} atkārtoti atvēra sarunu",
  "%{user_name} atlika sarunu",
  "%{user_name} atribuiu a si mesmo essa conversa",
  "%{user_name} atšauktas iš %{team_name}",
  "%{user_name} atšaukė pokalbio priskyrimą",
  "%{user_name} auto-asignado a esta conversación",
  "%{user_name} auto-atribuit această conversație",
  "%{user_name} auto-atribuída esta conversa",
  "%{user_name} beállította a prioritást erre: %{new_priority}",
  "%{user_name} bu konuşmayı kendisine atadı",
  "%{user_name} bỏ mức độ ưu tiên",
  "%{user_name} cambió la prioridad de %{old_priority} a %{new_priority}",
  "%{user_name} caur %{team_name} piešķīra sarunu %{assignee_name}",
  "%{user_name} changed the priority from %{old_priority} to %{new_priority}",
  "%{user_name} definiu a prioridade para %{new_priority}",
  "%{user_name} eliminat prioritatea",
  "%{user_name} eliminó la política de SLA %{sla_name}",
  "%{user_name} eliminó la prioridad",
  "%{user_name} eltávolított a prioritást",
  "%{user_name} estableció la prioridad a %{new_priority}",
  "%{user_name} fixe la priorité à %{new_priority}",
  "%{user_name} fjernet tildelingen til samtalen",
  "%{user_name} ha afegit la política de SLA %{sla_name}",
  "%{user_name} ha aggiunto la policy SLA %{sla_name}",
  "%{user_name} ha canviat la prioritat de %{old_priority} a %{new_priority}",
  "%{user_name} ha eliminat la política de SLA %{sla_name}",
  "%{user_name} ha eliminat la prioritat",
  "%{user_name} ha establert la prioritat a %{new_priority}",
  "%{user_name} ha impostato la priorità su %{new_priority}",
  "%{user_name} ha modificato la priorità da %{old_priority} a %{new_priority}",
  "%{user_name} ha posposat la conversa",
  "%{user_name} ha rimosso la policy SLA %{sla_name}",
  "%{user_name} ha rimosso la priorità",
  "%{user_name} ha tret l'assignació de la conversa",
  "%{user_name} har tilldelat sig denna konversation",
  "%{user_name} hat SLA-Richtlinie %{sla_name} entfernt",
  "%{user_name} hat SLA-Richtlinie %{sla_name} hinzugefügt",
  "%{user_name} hat die Priorität auf %{new_priority} gesetzt",
  "%{user_name} hat die Priorität entfernt",
  "%{user_name} hat die Priorität von %{old_priority} zu %{new_priority} geändert",
  "%{user_name} hat sich dieses Gespräch selbst zugewiesen",
  "%{user_name} heeft dit gesprek aan zichzelf toegewezen",
  "%{user_name} iestatīja prioritāti uz %{new_priority}",
  "%{user_name} ilmottautui keskusteluun",
  "%{user_name} je dodal politiko SLA %{sla_name}",
  "%{user_name} je maknuo prioritet",
  "%{user_name} je nastavil prednost na %{new_priority}",
  "%{user_name} je odstranil politiko SLA %{sla_name}",
  "%{user_name} je odstranil prednost",
  "%{user_name} je pogovor označil kot čakajočega",
  "%{user_name} je pogovor označil za rešenega",
  "%{user_name} je postavio prioritet na %{new_priority}",
  "%{user_name} je preklical dodelitev pogovora",
  "%{user_name} je preložil pogovor",
  "%{user_name} je promijenio prioritet s %{old_priority} na %{new_priority}",
  "%{user_name} je samododelio sebe ovom razgovoru",
  "%{user_name} je spremenil prednost iz %{old_priority} v %{new_priority}",
  "%{user_name} je znova odprl pogovor",
  "%{user_name} magára osztotta ezt a beszélgetést",
  "%{user_name} menetapkan sendiri percakapan ini",
  "%{user_name} menghapus prioritasnya",
  "%{user_name} mengubah prioritas dari %{old_priority} ke %{new_priority}",
  "%{user_name} merkitsi keskustelun ratkaistuksi",
  "%{user_name} mudou a prioridade de %{old_priority} para %{new_priority}",
  "%{user_name} módosította a prioritást: %{old_priority} -> %{new_priority}",
  "%{user_name} nomainīja prioritāti no %{old_priority} uz %{new_priority}",
  "%{user_name} noņēma SLA politiku %{sla_name}",
  "%{user_name} noņēma piešķiršanu",
  "%{user_name} noņēma piešķiršanu %{team_name}",
  "%{user_name} noņēma prioritāti",
  "%{user_name} nustatė prioritetą į %{new_priority}",
  "%{user_name} pakeitė prioritetą iš %{old_priority} į %{new_priority}",
  "%{user_name} pašalino prioritetą",
  "%{user_name} phân công chính mình vào hội thoại này",
  "%{user_name} pievienoja SLA politiku %{sla_name}",
  "%{user_name} piešķīra sarunu %{assignee_name}",
  "%{user_name} piešķīra sarunu %{team_name}",
  "%{user_name} poistui keskustelusta",
  "%{user_name} priskyrė %{assignee_name}",
  "%{user_name} priskyrė %{assignee_name} per %{team_name}",
  "%{user_name} priskyrė %{team_name}",
  "%{user_name} przypisał się do tej rozmowy",
  "%{user_name} removed SLA policy %{sla_name}",
  "%{user_name} removed the priority",
  "%{user_name} removeu a política de SLA %{sla_name}",
  "%{user_name} removeu a política de SLA de %{sla_name}",
  "%{user_name} removeu a prioridade",
  "%{user_name} ráosztotta a beszélgetést: %{assignee_name}",
  "%{user_name} ráosztotta a beszélgetést: %{team_name}",
  "%{user_name} s'est auto-assigné cette conversation",
  "%{user_name} s'ha auto assignat aquesta conversa",
  "%{user_name} sarunu atzīmēja kā atrisinātu",
  "%{user_name} sarunu atzīmēja kā neapstiprinātu",
  "%{user_name} sau priskyrė šį pokalbį",
  "%{user_name} schimbat prioritatea de la %{old_priority} la %{new_priority}",
  "%{user_name} self-assigned this conversation",
  "%{user_name} selv-tildelte denne samtale",
  "%{user_name} set the priority to %{new_priority}",
  "%{user_name} setați prioritatea pentru a %{new_priority}",
  "%{user_name} sev piešķīra šo sarunu",
  "%{user_name} si je ta pogovor dodelil sebi",
  "%{user_name} si è assegnato a questa conversazione",
  "%{user_name} tarafından %{assignee_name} adına atandı",
  "%{user_name} tarafından %{team_name} adına atandı",
  "%{user_name} tarafından %{team_name} aracılığıyla %{assignee_name} adına atandı",
  "%{user_name} tarafından %{team_name} ataması kaldırıldı",
  "%{user_name} tarafından konuşmanın atanması kaldırıldı",
  "%{user_name} tetapkan prioritas untuk %{new_priority}",
  "%{user_name} thay đổi mức độ ưu tiên từ %{old_priority} thành %{new_priority}",
  "%{user_name} thiết lập độ ưu tiên thành %{new_priority}",
  "%{user_name} tilordnet seg denne samtalen",
  "%{user_name} ustawił priorytet na %{new_priority}",
  "%{user_name} usunął priorytet",
  "%{user_name} uudelleenavasi keskustelun",
  "%{user_name} von %{assignee_name} zugewiesen",
  "%{user_name} zmienił priorytet z %{old_priority} na %{new_priority}",
  "%{user_name} önceliği %{new_priority} olarak ayarladı",
  "%{user_name} önceliği %{old_priority} dan %{new_priority} olarak değiştirdi",
  "%{user_name} önceliği kaldırdı",
  "%{user_name} úthlutaði þessu samtali á sig",
  "%{user_name} видалив політику SLA %{sla_name}",
  "%{user_name} видалив пріоритет",
  "%{user_name} встановив пріоритет %{new_priority}",
  "%{user_name} добавил политику SLA %{sla_name}",
  "%{user_name} додав політику SLA %{sla_name}",
  "%{user_name} завершил диалог",
  "%{user_name} змінив пріоритет з %{old_priority} на %{new_priority}",
  "%{user_name} изменил приоритет с %{old_priority} на %{new_priority}",
  "%{user_name} исключил из %{team_name}",
  "%{user_name} назначил %{assignee_name} в %{team_name}",
  "%{user_name} назначил %{assignee_name} ответственным",
  "%{user_name} назначил %{team_name} ответственным",
  "%{user_name} назначил(а) разговор себе",
  "%{user_name} открыл заново диалог",
  "%{user_name} самостійно призначив цей діалог",
  "%{user_name} удалил политику SLA %{sla_name}",
  "%{user_name} удалил приоритет",
  "%{user_name} установил приоритет на %{new_priority}",
  "%{user_name} הגדיר את העדיפות ל-%{new_priority}",
  "%{user_name} הוסיף מדיניות SLA %{sla_name}",
  "%{user_name} הסיר את העדיפות",
  "%{user_name} הסיר מדיניות SLA %{sla_name}",
  "%{user_name} הקצה לעצמו את השיחה הזו",
  "%{user_name} שינה את העדיפות מ-%{old_priority} ל-%{new_priority}",
  "%{user_name} أزال الأولوية",
  "%{user_name} أزال سياسة مستوى الخدمة %{sla_name}",
  "%{user_name} أضاف سياسة مستوى الخدمة %{sla_name}",
  "%{user_name} اولویت را از %{old_priority} به %{new_priority} تغییر داد",
  "%{user_name} اولویت را حذف کرد",
  "%{user_name} اولویت را روی %{new_priority} تنظیم کرد",
  "%{user_name} این مکالمه را به خود اختصاص داد",
  "%{user_name} تم تعيينه تلقائياً لهذه المحادثة",
  "%{user_name} حدد الأولوية إلى %{new_priority}",
  "%{user_name} سیاست SLA %{sla_name} را اضافه کرد",
  "%{user_name} سیاست SLA %{sla_name} را حذف کرد",
  "%{user_name} غيّر الأولوية من %{old_priority} إلى %{new_priority}",
  "%{user_name} گفتگو را به %{assignee_name} اختصاص داد",
  "%{user_name} گفتگو را به %{team_name} اختصاص داد",
  "%{user_name} द्वारा %{assignee_name} लाई जिम्मा दिइयो",
  "%{user_name} द्वारा %{team_name} मार्फत %{assignee_name} लाई तोकिएको",
  "%{user_name} द्वारा %{team_name} लाई तोकिएको",
  "%{user_name} ले SLA नीति %{sla_name} थप्यो",
  "%{user_name} ले SLA नीति %{sla_name} हटाए",
  "%{user_name} ले निष्क्रियता भएको कारण कुराकानी समाधान गरेका छन्",
  "%{user_name} ले प्राथमिकता %{new_priority} मा सेट गर्यो",
  "%{user_name} ले प्राथमिकता %{old_priority} बाट %{new_priority} मा परिवर्तन गर्यो",
  "%{user_name} ले प्राथमिकता हटाए",
  "%{user_name} ले यो कुराकानी आफैमा जिम्मा लिएको छ",
  "%{user_name} অগ্রাধিকারটি %{new_priority} এ নির্ধারণ করেছেন",
  "%{user_name} অগ্রাধিকারটি %{old_priority} থেকে %{new_priority} এ পরিবর্তন করেছেন",
  "%{user_name} অগ্রাধিকারটি সরিয়েছেন",
  "%{user_name} এই কথোপকথনটি স্নুজ করেছেন",
  "%{user_name} কথোপকথনটি খোলা হয়েছে বলে চিহ্নিত করেছেন",
  "%{user_name} কথোপকথনটি পুনরায় চালু করেছেন",
  "%{user_name} কথোপকথনটি সমাধান করেছেন (%{reason})",
  "%{user_name} কথোপকথনটি সমাধান হয়েছে বলে চিহ্নিত করেছেন",
  "%{user_name} কথোপকথনটিকে অপেক্ষমাণ হিসেবে চিহ্নিত করেছেন",
  "%{user_name} কথোপকথনের দায়িত্ব মুক্ত করেছেন",
  "%{user_name} দ্বারা %{team_name} এর মাধ্যমে %{assignee_name}-কে অ্যাসাইন করা হয়েছে",
  "%{user_name} দ্বারা %{team_name} থেকে অপসারণ করা হয়েছে",
  "%{user_name} দ্বারা %{team_name}-এ অ্যাসাইন করা হয়েছে",
  "%{user_name} নিজেই এই কথোপকথনটি নিয়েছেন",
  "%{user_name} இதை %{assignee_name}க்கு ஒதுக்கியுள்ளார்",
  "%{user_name} இதை %{team_name}க்கு ஒதுக்கியுள்ளார்",
  "%{user_name} இதை ஒதுக்க படாத உரையாடளாக்கியுள்ளார்",
  "%{user_name} സംഭാഷണം തീർച്ചപ്പെടുത്താത്തതായി അടയാളപ്പെടുത്തി",
  "%{user_name} സംഭാഷണം നിയുക്തമല്ലാതാക്കി",
  '%{user_name} がSLAポリシー "%{sla_name}" を削除しました',
  '%{user_name} がSLAポリシー "%{sla_name}" を追加しました',
  "%{user_name} がこの会話を自身に割り当てました",
  '%{user_name} が優先度を "%{new_priority}" に設定しました',
  '%{user_name} が優先度を "%{old_priority}" から "%{new_priority}" に変更しました',
  "%{user_name} が優先度を削除しました",
  "%{user_name} によって %{assignee_name} に割り当てられました",
  "%{user_name} によって %{team_name} から割り当てが解除されました",
  "%{user_name} によって %{team_name} に割り当てられました",
  "%{user_name} によって %{team_name} 経由で %{assignee_name} に割り当てられました",
  "%{user_name} によって会話がスヌーズされました",
  "%{user_name} によって会話が保留にされました",
  "%{user_name} によって会話が再開されました",
  "%{user_name} によって会話は解決済みになりました",
  "%{user_name} によって割り当てが解除されました",
  "%{user_name} 取消了优先级",
  "%{user_name} 取消了對話的分配",
  "%{user_name} 取消連結了 Linear 議題 %{issue_id}",
  "%{user_name} 因無活動而將對話標記為已解決",
  "%{user_name} 将优先级从 %{old_priority} 更改为 %{new_priority}",
  "%{user_name} 将优先级设置为 %{new_priority}",
  "%{user_name} 將優先順序從 %{old_priority} 變更為 %{new_priority}",
  "%{user_name} 將優先順序設為 %{new_priority}",
  "%{user_name} 將對話分配給 %{assignee_name}",
  "%{user_name} 將對話分配給 %{team_name}",
  "%{user_name} 將對話從 %{team_name} 取消分配",
  "%{user_name} 將對話指派給自己",
  "%{user_name} 將對話標記為已解決",
  "%{user_name} 將對話標記為已解決（%{reason}）",
  "%{user_name} 將對話標記為已解決：%{reason}",
  "%{user_name} 將對話標記為待處理",
  "%{user_name} 將對話標記為開啟",
  "%{user_name} 將對話標記為開啟（%{reason}）",
  "%{user_name} 將對話設為延後處理",
  "%{user_name} 建立了 Linear 議題 %{issue_id}",
  "%{user_name} 新增了 SLA 政策 %{sla_name}",
  "%{user_name} 添加了 SLA 策略 %{sla_name}",
  "%{user_name} 移除了 SLA 政策 %{sla_name}",
  "%{user_name} 移除了 SLA 策略 %{sla_name}",
  "%{user_name} 移除了優先順序",
  "%{user_name} 自行分配这次会话",
  "%{user_name} 透過 %{team_name} 將對話分配給 %{assignee_name}",
  "%{user_name} 連結了 Linear 議題 %{issue_id}",
  "%{user_name} 重新開啟了對話",
  "%{user_name}, %{sla_name} adlı SLA politikasını kaldırdı",
  "%{user_name}님이 %{assignee_name}에게 배정했습니다",
  "%{user_name}님이 %{team_name}에 배정했습니다",
  "%{user_name}님이 %{team_name}에서 배정을 해제했습니다",
  "%{user_name}님이 %{team_name}을(를) 통해 %{assignee_name}에게 배정했습니다",
  "%{user_name}님이 Linear 이슈 %{issue_id}을(를) 생성했습니다",
  "%{user_name}님이 Linear 이슈 %{issue_id}을(를) 연결했습니다",
  "%{user_name}님이 Linear 이슈 %{issue_id}의 연결을 해제했습니다",
  "%{user_name}님이 SLA 정책 %{sla_name}을(를) 제거했습니다",
  "%{user_name}님이 SLA 정책 %{sla_name}을(를) 추가했습니다",
  "%{user_name}님이 대화 배정을 해제했습니다",
  "%{user_name}님이 대화를 다시 열었습니다",
  "%{user_name}님이 대화를 보류 중으로 표시했습니다",
  "%{user_name}님이 대화를 열림으로 표시했습니다",
  "%{user_name}님이 대화를 일시 중단했습니다",
  "%{user_name}님이 대화를 해결됨으로 표시했습니다",
  "%{user_name}님이 비활성으로 인해 대화를 해결됨으로 표시했습니다",
  "%{user_name}님이 우선순위를 %{new_priority}(으)로 설정했습니다",
  "%{user_name}님이 우선순위를 %{old_priority}에서 %{new_priority}(으)로 변경했습니다",
  "%{user_name}님이 우선순위를 제거했습니다",
  "%{user_name}님이 이 대화를 자기 자신에게 배정했습니다",
  "A beszélgetést %{user_name} elnémította",
  "A beszélgetést %{user_name} folyamatban lévőnek jelölte",
  "A beszélgetést gazdátlanná tette %{user_name}",
  "A beszélgetést lezárta %{user_name}",
  "A beszélgetést lezárta a rendszer mivel %{count} napja inaktív volt",
  "A beszélgetést megoldottra állította: %{contact_name}",
  "A beszélgetést újranyitotta %{user_name}",
  "A conversa foi aberta por %{user_name}",
  "A conversa foi marcada como aberta por %{user_name}",
  "A conversa foi marcada como aberta por %{user_name} (%{reason})",
  "A conversa foi marcada como resolvida pelo sistema devido a %{count} horas de inatividade",
  "A conversa foi marcada como resolvida pelo sistema devido a %{count} minutos de inatividade",
  "A conversa foi marcada como resolvida pelo sistema por ter %{count} dias de inatividade",
  "A conversa foi marcada como resolvida pelo sistema por ter %{count} horas de inatividade",
  "A conversa foi marcada como resolvida pelo sistema por ter %{count} minutos de inatividade",
  "A conversa foi marcada como resolvida por %{user_name} (%{reason})",
  "A conversa foi marcada como resolvida por %{user_name} devido à inatividade",
  "A conversa foi marcada como resolvida por %{user_name} por inatividade",
  "A conversa foi marcada como resolvida por %{user_name}: %{reason}",
  'A conversa foi marcada como resolvida porque a tarefa vinculada "%{task_title}" no funil "%{board_name}" foi ganha',
  "A conversa foi resolvida por %{contact_name}",
  "A envoyé une demande d'autorisation d'appel à %{contact_name}.",
  "Ang pag-uusap ay tinakdang bukas ni %{user_name}",
  "Ang pag-uusap ay tinakdang tapos ng sistema dahil sa %{count} araw ng hindi pagkilos",
  "Ang pag-uusap ay tinakdang tapos ng sistema dahil sa %{count} minuto ng hindi pagkilos",
  "Ang pag-uusap ay tinakdang tapos ng sistema dahil sa %{count} oras ng hindi pagkilos",
  "Ang pag-uusap ay tinakdang tapos ni %{user_name} (%{reason})",
  "Ang pag-uusap ay tinakdang tapos ni %{user_name} dahil sa kawalan ng aktibidad",
  "Asignado a %{assignee_name} por %{user_name}",
  "Asignado a %{assignee_name} via %{team_name} por %{user_name}",
  "Asignado a %{team_name} por %{user_name}",
  "Assegnata a %{assignee_name} via %{team_name} da %{user_name}",
  "Assegnata a %{team_name} da %{user_name}",
  "Assegnato a %{assignee_name} da %{user_name}",
  "Assegnazione a %{team_name} rimossa da %{user_name}",
  "Assignada a %{assignee_name} per %{user_name}",
  "Assignada a %{team_name} per %{user_name}",
  "Assignat a %{assignee_name} mitjançant %{team_name} per %{user_name}",
  "Assigned to %{assignee_name} by %{user_name}",
  "Assigned to %{assignee_name} via %{team_name} by %{user_name}",
  "Assigned to %{team_name} by %{user_name}",
  "Assigné à %{assignee_name} par %{user_name}",
  "Assigné à %{assignee_name} via %{team_name} par %{user_name}",
  "Assigné à %{team_name} par %{user_name}",
  "Atribuit %{assignee_name} prin %{team_name} de către %{user_name}",
  "Atribuit lui %{assignee_name} de %{user_name}",
  "Atribuit lui %{team_name} de %{user_name}",
  "Atribuído a %{assignee_name} por %{user_name}",
  "Atribuído a %{assignee_name} via %{team_name} por %{user_name}",
  "Atribuído a %{team_name} por %{user_name}",
  "Binago ni %{user_name} ang prayoridad mula %{old_priority} patungong %{new_priority}",
  "Binuksan ang pag-uusap ni %{user_name} (%{reason})",
  "Biseda u shënua si e hapur nga %{user_name}",
  "Biseda u shënua si e zgjidhur nga %{user_name} për shkak të mungesës së aktivitetit",
  "Biseda u shënua si e zgjidhur nga sistemi për %{count} minuta pa aktivitet",
  "Biseda u shënua si e zgjidhur nga sistemi për %{count} orë pa aktivitet",
  "Caso Linear %{issue_id} foi associado por %{user_name}",
  "Caso Linear %{issue_id} foi criado por %{user_name}",
  "Caso Linear %{issue_id} foi desassociado por %{user_name}",
  "Chỉ định %{assignee_name} bởi %{user_name}",
  "Chỉ định %{team_name} bởi %{user_name}",
  "Conversa adiada por %{user_name}",
  "Conversa auto-resolvida pelo sistema por causa dos %{count} dias sem inatividade",
  "Conversa desatribuída por %{user_name}",
  "Conversa foi adiada por %{user_name}",
  "Conversa foi marcada como pendente por %{user_name}",
  "Conversa foi marcada como resolvida por %{user_name}",
  "Conversa foi reaberta por %{user_name}",
  "Conversa foi resolvida por %{contact_name}",
  "Conversa marcada como pendente por %{user_name}",
  "Conversa não atribuída por %{user_name}",
  "Conversación fue resuelta por %{contact_name}",
  "Conversación no asignada por %{user_name}",
  "Conversation unassigned by %{user_name}",
  "Conversation was marked as pending by %{user_name}",
  "Conversation was marked open by %{user_name}",
  "Conversation was marked open by %{user_name} (%{reason})",
  'Conversation was marked resolved because the linked task "%{task_title}" on funnel "%{board_name}" was won',
  "Conversation was marked resolved by %{user_name}",
  "Conversation was marked resolved by %{user_name} (%{reason})",
  "Conversation was marked resolved by %{user_name} due to inactivity",
  "Conversation was marked resolved by %{user_name}: %{reason}",
  "Conversation was marked resolved by system due to %{count} days of inactivity",
  "Conversation was marked resolved by system due to %{count} hours of inactivity",
  "Conversation was marked resolved by system due to %{count} minutes of inactivity",
  "Conversation was reopened by %{user_name}",
  "Conversation was resolved by %{contact_name}",
  "Conversation was snoozed by %{user_name}",
  "Conversazione disassegnata da %{user_name}",
  "Conversația a fost marcată ca fiind în așteptare de către %{user_name}",
  "Conversația a fost marcată de %{user_name}",
  "Conversația a fost marcată de sistem din cauza %{count} zile de inactivitate",
  "Conversația a fost redeschisă de %{user_name}",
  "Conversația a fost rezolvată de %{contact_name}",
  "Conversația a fost snoozed de %{user_name}",
  "Conversație neasociată de %{user_name}",
  "Cuộc hội thoại chưa được chỉ định bởi %{user_name}",
  "Cuộc trò chuyện đã được mở lại bởi %{user_name}",
  "Cuộc trò chuyện được đánh dấu là đã giải quyết bởi %{user_name}",
  "Das Gespräch wurde vom System aufgrund von %{count} Tagen Inaktivität gelöst",
  "Das Gespräch wurde von %{user_name} als ausstehend markiert",
  "Das Gespräch wurde von %{user_name} gelöst",
  "Das Gespräch wurde von %{user_name} wieder eröffnet",
  "Das Gespräch wurde von %{user_name} zur Erinnerung markiert",
  "Delegoitu edustajalle %{assignee_name} edustajan %{user_name} toimesta",
  "Delegoitu edustajalle %{team_name} edustajan %{user_name} toimesta",
  "Desasignado de %{team_name} por %{user_name}",
  "Desatribuído de %{team_name} por %{user_name}",
  "Dibebastugaskan dari %{team_name} oleh %{user_name}",
  "Ditugaskan ke %{assignee_name} melalui %{team_name} oleh %{user_name}",
  "Ditugaskan ke %{assignee_name} oleh %{user_name}",
  "Ditugaskan ke %{team_name} oleh %{user_name}",
  "Dodelitev uporabniku %{user_name} preklicana s strani %{team_name}",
  "Dodeljeno %{assignee_name} od strane %{user_name}",
  "Dodeljeno %{assignee_name} putem %{team_name} od strane %{user_name}",
  "Dodeljeno %{team_name} od strane %{user_name}",
  "Dodeljeno %{team_name} s strani %{user_name}",
  "Dodeljeno %{user_name} s strani %{assignee_name}",
  "Dodeljeno%{assignee_name} preko %{team_name} s strani %{user_name}",
  "Eine Anfrage zur Anrufberechtigung wurde an %{contact_name} gesendet.",
  "El sistema ha marcat que la conversa s'ha resolt a causa de %{count} dies d'inactivitat",
  "Entfernt aus %{team_name} von %{user_name}",
  "Envió una solicitud de permiso de llamada a %{contact_name}.",
  "Gesprek niet toegewezen door %{user_name}",
  "Gesprek werd door systeem gemarkeerd als opgelost na %{count} dagen inactiviteit",
  "Gesprek werd gemarkeerd als in afwachting door %{user_name}",
  "Gesprek werd gemarkeerd door %{user_name}",
  "Gesprek werd gesluimerd door %{user_name}",
  "Gesprek werd heropend door %{user_name}",
  "Gesprek werd opgelost door %{contact_name}",
  "Gespräch nicht zugewiesen von %{user_name}",
  "Hindi na itinalaga ang pag-uusap ni %{user_name}",
  "Hozzárendelve ehhez: %{assignee_name} ezen csoportból %{team_name} általa: %{user_name}",
  "Hozzárendelés megszüntetve: %{team_name} általa: %{user_name}",
  "Huỷ phân công cho %{team_name} bởi %{user_name}",
  "Hội thoại đã được giải quyết bởi %{contact_name}",
  "Hội thoại đã được tạm dừng lại bởi %{user_name}",
  "Hội thoại được đánh dấu là chưa giải quyết bởi %{user_name}",
  "Hội thoại được đánh dấu là đã giải quyết bởi hệ thống vì %{count} ngày không hoạt động",
  "Idinagdag ni %{user_name} ang patakaran ng SLA na %{sla_name}",
  "Ikke tildelt fra %{team_name} af %{user_name}",
  "Inalis mula sa %{team_name} ni %{user_name}",
  "Inalis ni %{user_name} ang patakaran ng SLA na %{sla_name}",
  "Inalis ni %{user_name} ang prayoridad",
  "Inatasan ni %{user_name} ang sarili sa pag-uusap na ito",
  "Issue Linear %{issue_id} è stata collegata da %{user_name}",
  "Issue Linear %{issue_id} è stata creata da %{user_name}",
  "Issue Linear %{issue_id} è stata scollegata da %{user_name}",
  "Itinakda ni %{user_name} ang prayoridad sa %{new_priority}",
  "Itinalaga kay %{assignee_name} ni %{user_name}",
  "Itinalaga kay %{assignee_name} sa pamamagitan ng %{team_name} ni %{user_name}",
  "Itinalaga sa %{team_name} ni %{user_name}",
  "Keskustelu merkittiin ratkaistuksi automaattisesti, sillä on kulunut %{count} päivää viimeisestä viestistä",
  "Konuşma %{contact_name} tarafından çözümlendi olarak işaretlendi",
  "Konuşma %{user_name} tarafından açık olarak işaretlendi",
  "Konuşma %{user_name} tarafından çözümlendi olarak işaretlendi",
  "Konuşma, %{count} dakikalık hareketsizlik nedeniyle sistem tarafından çözümlendi olarak işaretlendi",
  "Konuşma, %{count} günlük hareketsizlik nedeniyle sistem tarafından çözümlendi olarak işaretlendi",
  "Konuşma, %{count} saatlik hareketsizlik nedeniyle sistem tarafından çözümlendi olarak işaretlendi",
  "Konuşma, %{user_name} tarafından açık olarak işaretlendi",
  "Konuşma, %{user_name} tarafından bekleyen olarak işaretlendi",
  "Konuşma, %{user_name} tarafından erteledi olarak işaretlendi",
  "Konuşma, %{user_name} tarafından etkinlik olmadığı için çözüldü olarak işaretlendi",
  "Konversation otilldelad av %{user_name}",
  "Konversation wurde von %{contact_name} gelöst",
  "Konversationen har markerats som löst av %{user_name}",
  "Konversationen har markerats som löst av systemet på grund av %{count} dagars inaktivitet",
  "Konversationen öppnades igen av %{user_name}",
  "Konverzace byla vyřešena uživatelem %{user_name}",
  "Konverzace byla znovu otevřena uživatelem %{user_name}",
  "Konverzace zrušena uživatelem %{user_name}",
  "Konverzácia nepriradená %{user_name}",
  "La conversa es va reobrir per %{user_name}",
  "La conversa va ser marcada com pendent per %{user_name}",
  "La conversa va ser marcada com resolta per %{user_name}",
  "La conversa va ser resolta per %{contact_name}",
  "La conversación fue marcada como pendiente por %{user_name}",
  "La conversación fue marcada por %{user_name}",
  "La conversación fue marcada por el sistema debido a %{count} días de inactividad",
  "La conversación fue pospuesta por %{user_name}",
  "La conversación fue reabierta por %{user_name}",
  'La conversación se marcó como resuelta porque la tarea vinculada "%{task_title}" del embudo "%{board_name}" se ganó',
  "La conversation a été marquée comme en attente par %{user_name}",
  "La conversation a été marquée comme résolue par le système en raison de %{count} heures d'inactivité",
  "La conversation a été marquée comme résolue par le système en raison de %{count} jours d'inactivité",
  "La conversation a été marquée comme résolue par le système en raison de %{count} minutes d'inactivité",
  "La conversation a été marquée ouverte par %{user_name}",
  "La conversation a été marquée ouverte par %{user_name} (%{reason})",
  "La conversation a été marquée résolue par %{user_name}",
  "La conversation a été marquée résolue par %{user_name} (%{reason})",
  "La conversation a été marquée résolue par %{user_name} en raison de l'inactivité",
  "La conversation a été marquée résolue par %{user_name}: %{reason}",
  "La conversation a été reportée par %{user_name}",
  "La conversation a été ré-ouverte par %{user_name}",
  "La conversation a été résolue par %{contact_name}",
  "La conversazione è stata aperta da %{user_name} (%{reason})",
  "La conversazione è stata contrassegnata come in attesa da %{user_name}",
  "La conversazione è stata contrassegnata come risolta da %{user_name}",
  "La conversazione è stata contrassegnata come risolta dal sistema a causa di %{count} giorni d'inattività",
  "La conversazione è stata contrassegnata come risolta dal sistema a causa di %{count} minuti d'inattività",
  "La conversazione è stata contrassegnata come risolta dal sistema a causa di %{count} ore d'inattività",
  "La conversazione è stata posticipata da %{user_name}",
  "La conversazione è stata riaperta da %{user_name}",
  "La conversazione è stata risolta da %{contact_name}",
  "La conversazione è stata risolta da %{user_name} (%{reason})",
  "La conversazione è stata risolta da %{user_name}: %{reason}",
  "La conversazione è stata segnata risolta da %{user_name} per inattività",
  "Le ticket Linear %{issue_id} a été créé par %{user_name}",
  "Le ticket Linear %{issue_id} a été dissocié par %{user_name}",
  "Le ticket Linear %{issue_id} a été lié par %{user_name}",
  "Linear issue %{issue_id} was created by %{user_name}",
  "Linear issue %{issue_id} was linked by %{user_name}",
  "Linear issue %{issue_id} was unlinked by %{user_name}",
  "Linear sorun %{issue_id} %{user_name} tarafından bağlandı",
  "Linear sorun %{issue_id} %{user_name} tarafından bağlantısı kaldırıldı",
  "Linear sorun %{issue_id} %{user_name} tarafından oluşturuldu",
  "Linear ইস্যু %{issue_id} আনলিঙ্ক করেছেন %{user_name}",
  "Linear ইস্যু %{issue_id} তৈরি করেছেন %{user_name}",
  "Linear ইস্যু %{issue_id} লিঙ্ক করেছেন %{user_name}",
  "Mengirim permintaan izin panggilan ke %{contact_name}.",
  "Muling binuksan ang pag-uusap ni %{user_name}",
  "Nalutas ang pag-uusap ni %{contact_name}",
  "Neatribuit de la %{team_name} de către %{user_name}",
  "Non assigné de %{team_name} par %{user_name}",
  "Não atribuído a %{team_name} por %{user_name}",
  "Odpriradené z %{team_name} od %{user_name}",
  "Percakapan batal ditetapkan oleh %{user_name}",
  "Percakapan diselesaikan oleh %{contact_name}",
  "Percakapan ditandai selesai oleh %{user_name}",
  "Percakapan ditandai terselesaikan oleh sistem karena tidak ada aktifitas dalam %{count} hari",
  "Percakapan telah dibuka kembali oleh %{user_name}",
  "Percakapan telah ditandai sebagai tertunda oleh %{user_name}",
  "Percakapan telah ditunda oleh %{user_name}",
  "Phân công cho %{assignee_name} thông qua %{team_name} bởi %{user_name}",
  "Pogovor je razrešil %{contact_name}",
  "Pokalbį atidėjo %{user_name}",
  "Pokalbį iš naujo pradėjo %{user_name}",
  "Pokalbį pažymėjo %{user_name} kaip baigtą",
  "Pokalbį pažymėjo %{user_name} kaip laukiantį",
  "Pokalbį užbaigė %{contact_name}",
  "Pridelené %{assignee_name} od %{user_name}",
  "Pridelené %{assignee_name} prostredníctvom %{team_name} od %{user_name}",
  "Pridelené %{team_name} od %{user_name}",
  "Problema linear %{issue_id} foi criado por %{user_name}",
  "Problema linear %{issue_id} foi desvinculado por %{user_name}",
  "Problema linear %{issue_id} foi vinculado por %{user_name}",
  "Przydzielone do %{team_name} przez %{user_name}",
  "Przypisane do %{assignee_name} przez %{user_name}",
  "Przypisano do %{assignee_name} przez %{team_name} przez %{user_name}",
  "Přiřazeno k %{assignee_name} uživatelem %{user_name}",
  "Razgovor je odložen od strane %{user_name}",
  "Razgovor je označen kao na čekanju od strane %{user_name}",
  "Razgovor je označen kao rešen od strane %{user_name}",
  "Razgovor je označen kao rešen od strane sistema zbog %{count} dana neaktivnosti",
  "Razgovor je ponovo otvoren od strane %{user_name}",
  "Razgovor je rešen od strane %{contact_name}",
  "Razgovoru uklonjena dodela od strane %{user_name}",
  "Responsable de la conversation supprimé par %{user_name}",
  "Richiesta di autorizzazione di chiamata inviata a %{contact_name}.",
  "Rozmowa nieprzypisana przez %{user_name}",
  "Rozmowa została oznaczona jako oczekująca przez %{user_name}",
  "Rozmowa została oznaczona przez %{user_name}",
  "Rozmowa została oznaczona przez system jako rozwiązana z powodu %{count} dni bezczynności",
  "Rozmowa została ponownie otwarta przez %{user_name}",
  "Rozmowa została rozwiązana przez %{contact_name}",
  "Rozmowa została uśpiona przez %{user_name}",
  "Samtal var leyst af %{contact_name}",
  "Samtal var merkt sem leyst af %{user_name}",
  "Samtal var merkt sem leyst af kerfinu vegna óvirkni í %{count} daga",
  "Samtal var merkt sem í bið af %{user_name}",
  "Samtale ble automatisk merket løst på grunn av %{count} dager med inaktivitet",
  "Samtale ble løst av %{user_name}",
  "Samtale fjernet tildeling af %{user_name}",
  "Samtalen ble gjenåpnet av %{user_name}",
  "Samtalen blev genåbnet af %{user_name}",
  "Samtalen blev løst af %{contact_name}",
  "Samtalen blev markeret som afventende af %{user_name}",
  "Samtalen blev markeret som løst af %{user_name}",
  "Samtalen blev markeret som løst af systemet på grund af %{count} dages inaktivitet",
  "Samtalen blev udskudt af %{user_name}",
  "Sense assignar des de %{team_name} per %{user_name}",
  "Sent a call permission request to %{contact_name}.",
  "Sistem je označil pogovor kot razrešen zaradi %{count} dni nedejavnosti",
  "Sistema pokalbį pažymėjo kaip baigtą dėl %{count} neaktyvumo dienų",
  "Sistēma sarunu atzīmēja kā atrisinātu %{count} dienu neaktivitātes dēļ",
  "Solicitação de permissão de chamada enviada para %{contact_name}.",
  "Tildelt %{assignee_name} af %{user_name}",
  "Tildelt %{assignee_name} via %{team_name} af %{user_name}",
  "Tildelt %{team_name} af %{user_name}",
  "Tildelt til %{assignee_name} av %{user_name}",
  "Tildelt til %{team_name} av %{user_name}",
  "Tilldelad till %{assignee_name} av %{user_name}",
  "Tinukoy bilang nalutas ang pag-uusap ni %{user_name}",
  "Tinukoy na nalutas ang pag-uusap ni %{user_name}: %{reason}",
  "Toegewezen aan %{assignee_name} door %{user_name}",
  "Toegewezen aan %{assignee_name} via %{team_name} door %{user_name}",
  "Toegewezen aan %{team_name} door %{user_name}",
  "Uklonjena dodela %{team_name} od strane %{user_name}",
  "Unassigned from %{team_name} by %{user_name}",
  "Usunięto przydzielenie do %{team_name} przez %{user_name}",
  "Zugewiesen an %{assignee_name} über %{team_name} von %{user_name}",
  "Zugewiesen an %{team_name} von %{user_name}",
  "Çështja në Linear %{issue_id} u krijua nga %{user_name}",
  "Çështja në Linear %{issue_id} u lidh nga %{user_name}",
  "Çështja në Linear %{issue_id} u shkëput nga %{user_name}",
  "Óúthlutað af %{team_name} af %{user_name}",
  "Úthlutað %{assignee_name} í gegnum %{team_name} af %{user_name}",
  "Úthlutað á %{assignee_name} af %{user_name}",
  "Έγινε επαναφορά της συνομιλίας από τον %{user_name}",
  "Ανατέθηκε στον %{assignee_name} από τον %{user_name}",
  "Ανατέθηκε στον %{assignee_name} μέσω %{team_name} από %{user_name}",
  "Ανατέθηκε στον %{team_name} από τον %{user_name}",
  "Από-ανατέθηκε στον %{team_name} από %{user_name}",
  "Η συνομιλία έχει επιλυθεί από τον %{user_name}",
  "Η συνομιλία επιλύθηκε από τον %{contact_name}",
  "Η συνομιλία επισημάνθηκε ως εκκρεμής από τον %{user_name}",
  "Η συνομιλία σημάνθηκε επιλυθείσα από το σύστημα με την παρέλευση %{count} ημερών άνευ δραστηριότητας",
  'Η συνομιλία σημάνθηκε ως "καθυστερημένη" (snoozed) από τον %{user_name}',
  "Η συνομιλία σημάνθηκε ως μη ανατεθειμένη από τον %{user_name}",
  "Ο χρήστης %{user_name} ανέλαβε αυτήν την συνομιλία",
  "Бесіда була позначена як очікується %{user_name}",
  "Виключений з %{team_name} користувачем %{user_name}",
  "Диалог был завершен %{user_name} с причиной: %{reason}",
  "Диалог был открыт %{user_name}",
  "Диалог был решен %{user_name} из-за бездействия",
  "Диалог был решен системой из-за %{count} часов бездействия",
  "Диалог был решён системой из-за %{count} минут бездействия",
  "Діалог був закритий %{contact_name}",
  "Діалог був закритий системою через %{count} днів неактивності",
  "Діалог знято %{user_name}",
  "Линейная задача %{issue_id} была отвязана от %{user_name}",
  "Линейная задача %{issue_id} была связана с %{user_name}",
  "Линейная задача %{issue_id} была создана %{user_name}",
  "Ответственный снят %{user_name}",
  "Отправлен запрос на разрешение на звонок %{contact_name}.",
  "Призначено до %{assignee_name} користувачем %{user_name}",
  "Призначено до %{assignee_name} користувачем %{user_name} з %{team_name}",
  "Призначено до %{team_name} користувачем %{user_name}",
  "Разговор был закрыт %{contact_name}",
  "Разговор был помечен как ожидающий %{user_name}",
  "Разговор был помечен как отложенный %{user_name}",
  "Разговор был помечен системой решённым из-за неактивности в течение %{count} дней",
  "Розмова була відкладена %{user_name}",
  "Розмова була відмічена як вирішена %{user_name}",
  "Розмову знову відкрито %{user_name}",
  "ביטול הקצאה של שיחה על ידי %{user_name}",
  "בעיית Linear %{issue_id} נוצרה על ידי %{user_name}",
  "בעיית Linear %{issue_id} נותקה על ידי %{user_name}",
  "בעיית Linear %{issue_id} קושרה על ידי %{user_name}",
  "הוקצה ל-%{assignee_name} דרך %{team_name} על ידי %{user_name}",
  "הוקצה ל-%{assignee_name} על ידי %{user_name}",
  "הוקצה ל-%{team_name} על ידי %{user_name}",
  "השיחה הושהתה על ידי %{user_name}",
  "השיחה נפתחה מחדש על ידי %{user_name}",
  "השיחה נפתרה על ידי %{contact_name}",
  "השיחה סומנה כממתינה על ידי %{user_name}",
  "השיחה סומנה כפתוחה על ידי %{user_name}",
  "השיחה סומנה כפתורה על ידי %{user_name}",
  "השיחה סומנה כפתורה על ידי %{user_name} עקב חוסר פעילות",
  "השיחה סומנה כפתורה על ידי המערכת עקב חוסר פעילות של %{count} דקות",
  "השיחה סומנה כפתורה על ידי המערכת עקב חוסר פעילות של %{count} ימים",
  "השיחה סומנה כפתורה על ידי המערכת עקב חוסר פעילות של %{count} שעות",
  "לא הוקצה מ-%{team_name} על ידי %{user_name}",
  "إلغاء التعيين من %{team_name} بواسطة %{user_name}",
  "اختصاص داده نشده از %{team_name} توسط %{user_name}",
  "از طرف %{user_name} به تیم %{team_name} و ایجنت %{assignee_name} اختصاص داده شده است",
  "المحادثة غير مسندة بواسطة %{user_name}",
  "به دلیل %{count} روز عدم فعالیت ، مکالمه توسط سیستم بسته شد",
  "تم إسنادها إلى %{assignee_name} بواسطة %{user_name}",
  "تم إسنادها إلى %{team_name} بواسطة %{user_name}",
  "تم إعادة فتح المحادثة بواسطة %{user_name}",
  "تم تأجيل المحادثة بواسطة %{user_name}",
  'تم تحديث حالة المحادثة لـ"معلقة" بواسطة %{user_name}',
  'تم تحديث حالة المحادثة لـ"مغلقة" بواسطة %{user_name}',
  "تم تحديد هذه المحادثة كمحلولة بواسطة %{user_name} بسبب عدم النشاط",
  "تم تحديد هذه المحادثة كمحلولة بواسطة النظام بسبب عدم النشاط لمدة %{count} دقائق",
  "تم تحديد هذه المحادثة كمحلولة بواسطة النظام بسبب عدم النشاط لمدة %{count} ساعات",
  "تم تحديد هذه المحادثة كمفتوحة بواسطة %{user_name}",
  "تم تعيينه إلى %{assignee_name} عبر %{team_name} بواسطة %{user_name}",
  "تم حل المحادثة بواسطة %{contact_name}",
  "تم وضع علامة على المحادثة كمحلولة من قبل النظام بسبب %{count} أيام من عدم النشاط",
  "مکالمه توسط %{user_name} به تعویق افتاد",
  "مکالمه توسط %{user_name} به عنوان معلق علامت گذاری شد",
  "مکالمه توسط ایجنت %{user_name} حل شده، اعلام شده بود",
  "گفتگو توسط %{contact_name} حل شد",
  "گفتگو توسط اپراتور %{user_name} به وضعیت اختصاص داده نشده تغییر یافت",
  "گفتگو توسط ایجنت %{user_name} مجددا باز شده بود",
  "कुराकानी %{count} दिन निष्क्रिय भएकाले प्रणालीले समाधान गरेको छ",
  "कुराकानी %{user_name} द्वारा खुला चिन्ह लगाइयो (%{reason})",
  "कुराकानी %{user_name} द्वारा समाधान गरिएको चिन्ह लगाइयो (%{reason})",
  "कुराकानी %{user_name} द्वारा सुताइएको थियो",
  "कुराकानीलाई %{count} घण्टा निष्क्रिय रहेकाले प्रणालीले समाधान गरेको हो",
  "कुराकानीलाई %{count} मिनेट निष्क्रिय रहेकाले प्रणालीले समाधान गरेको हो",
  "संवाद %{contact_name} द्वारा समाधान गरियो",
  "संवाद %{user_name} द्वारा जिम्मा हटाइयो",
  "संवाद %{user_name} द्वारा समाधान गरिएको चिन्ह लगाइएको छ: %{reason}",
  "আলোচনা %{user_name} দ্বারা খোলা হয়েছে (%{reason})",
  "আলোচনাটি %{user_name} দ্বারা সমাধান হয়েছে: %{reason}",
  "নিষ্ক্রিয়তার কারণে %{user_name} কথোপকথনটি সমাধান হয়েছে বলে চিহ্নিত করেছেন",
  "সিস্টেম %{count} ঘণ্টা নিষ্ক্রিয় থাকার কারণে কথোপকথনটি সমাধান হয়েছে বলে চিহ্নিত করেছে",
  "সিস্টেম %{count} দিন নিষ্ক্রিয় থাকার কারণে কথোপকথনটি সমাধান হয়েছে বলে চিহ্নিত করেছে",
  "সিস্টেম %{count} মিনিট নিষ্ক্রিয় থাকার কারণে কথোপকথনটি সমাধান হয়েছে বলে চিহ্নিত করেছে",
  "உரையாடலுக்கு %{user_name} தீர்வு வழங்கியுள்ளார்",
  "உரையாடலை %{user_name} மீண்டும் திறந்துள்ளார்",
  "സംഭാഷണം %{user_name} പരിഹരിച്ചതായി അടയാളപ്പെടുത്തി",
  "സംഭാഷണം %{user_name} വീണ്ടും തുറന്നു",
  "对话未被 %{user_name} 分配",
  "对话被 %{contact_name} 重新打开",
  "对话被 %{user_name} 打开",
  "对话被 %{user_name} 暂停",
  "对话被 %{user_name} 重新打开",
  "对话被标记由 %{user_name} 待处理",
  "对话被标记由 %{user_name} 解决",
  "对话被系统标记为已解决, 原因是 %{count} 分钟不活跃",
  "对话被系统标记为已解决, 原因是 %{count} 天不活跃",
  "对话被系统标记为已解决, 原因是 %{count} 小时不活跃",
  "对话被系统标记为已解决, 原因是 %{user_name} 不活跃",
  "由 %{user_name} 从 %{team_name} 中取消分配",
  "由 %{user_name} 分配给 %{assignee_name}",
  "由 %{user_name} 分配给 %{team_name}",
  "由 %{user_name} 通过 %{team_name} 团队分配给 %{assignee_name}",
  "由於對話已經 %{count} 分鐘沒有新活動，已被系統標記為已解決",
  "由於對話已經 %{count} 天沒有新活動，已被系統標記為已解決",
  "由於對話已經 %{count} 小時沒有新活動，已被系統標記為已解決",
  "대화가 %{user_name}에 의해 열림으로 표시되었습니다 (%{reason})",
  "대화가 %{user_name}에 의해 해결됨으로 표시되었습니다 (%{reason})",
  "대화가 %{user_name}에 의해 해결됨으로 표시되었습니다: %{reason}",
];

// `%{user_name}` and every other placeholder is somebody's name, which we never need; `%{labels}` is
// the run. Anchored at both ends, so a sentence that merely CONTAINS a template's words does not
// match it.
function compile(templates: readonly string[]): RegExp[] {
  return templates.map(
    (t) =>
      new RegExp(
        `^${t
          .split(/(%\{\w+\})/g)
          .map((part) =>
            part === "%{labels}"
              ? "(.+)"
              : /^%\{\w+\}$/.test(part)
                ? "(?:.+?)"
                : part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"),
          )
          .join("")}$`,
        "u",
      ),
  );
}

const LABEL_ACTIVITY_PATTERNS: readonly RegExp[] = compile(
  LABEL_ACTIVITY_TEMPLATES,
);
const OTHER_ACTIVITY_PATTERNS: readonly RegExp[] = compile(
  OTHER_ACTIVITY_TEMPLATES,
);

// EVERY READING OF THIS LINE AS A LABEL CHANGE, not the first one (round 7). Two locales can render
// sentences that differ only by a word the other one puts inside `%{labels}`: Portuguese ships both
// "%{user_name} removeu %{labels}" (pt_BR) and "%{user_name} removeu a %{labels}" (pt), so "Ana
// removeu a vip" parses as the label "a vip" under one and "vip" under the other. Returning the
// first match hid every Portuguese removal behind a title no account has. The caller decides which
// reading is real by asking its own catalog, which is the only thing that can tell them apart.
//
// Empty when no template rendered this line. The SEPARATOR is Chatwoot's own `", "`, so a title
// containing a comma and a space is split here and then fails the caller's catalog check, which is
// a miss and not a wrong reading.
export function labelsNarrated(content: string): string[][] {
  const line = content.trim();
  if (line.length === 0) return [];
  if (OTHER_ACTIVITY_PATTERNS.some((re) => re.test(line))) return [];
  const readings: string[][] = [];
  const seen = new Set<string>();
  for (const re of LABEL_ACTIVITY_PATTERNS) {
    const m = line.match(re);
    if (m?.[1] === undefined) continue;
    const titles = m[1].split(", ").map((t) => t.trim());
    if (!titles.every((t) => t.length > 0)) continue;
    const key = titles.join("\u0000");
    if (seen.has(key)) continue;
    seen.add(key);
    readings.push(titles);
  }
  return readings;
}

// Test-only: the templates exactly as this module compiles them, so a test can assert that what is
// vendored here is what Chatwoot renders — an apostrophe escaped by doubling it in a single-quoted
// YAML scalar is the shape that reaches here wrong and shows up nowhere else (round 10).
export const __templatesForTest = {
  labels: LABEL_ACTIVITY_TEMPLATES,
  other: OTHER_ACTIVITY_TEMPLATES,
};
