import table from "./model-prices.json";

// WHAT ONE MODEL CALL COST, in USD, from the price table in this folder (issue #863). Priced when the
// ledger row is written, from that row's own token counts, so a turn's cost is known the moment the
// turn ends, which the Langfuse cost the dashboard and the spend ceiling read is not (its ingestion is
// asynchronous, and it answers per observation behind pagination and a rate limit).
//
// The table is LiteLLM's, regenerated by `scripts/refresh-model-prices.ts` and pinned to the commit
// it was read at (`PRICES_SOURCE`, `PRICES_READ_AT`). It was checked against the vendors' own pages
// for the provider defaults on the day it was read; the fence in tests/modules/pricing.test.ts holds
// those rows to what the vendor said.
//
// A call the table cannot price is `null`, never zero: a zero enters every total it is summed into
// and the total then claims to be whole. That covers a model the table does not name, a provider it
// cannot speak for (`openai-compatible` is whatever the operator's server is), and a call that used
// a rate the model's row does not carry (cache writes on a model with no cache-write price).

type Rates = {
  input: number;
  cachedInput?: number;
  cacheWrite?: number;
  output: number;
};
type Entry = Rates & { tiers?: (Rates & { above: number })[] };

const MODELS = table.models as Record<string, Entry>;

export const PRICES_SOURCE: string = table.source;
export const PRICES_READ_AT: string = table.readAt;

export interface PricedTokens {
  promptTokens: number;
  cachedReadTokens: number;
  cacheCreationTokens: number;
  completionTokens: number;
}

// Where a provider's model lives in the table. The table is keyed the way LiteLLM routes, so the same
// model id means different rows for different providers: Google's AI Studio rows carry `gemini/`, and
// OpenRouter's carry `openrouter/` in front of the vendor-prefixed id OpenRouter itself uses.
function tableKeys(provider: string, model: string): string[] {
  switch (provider) {
    case "openai":
    case "anthropic":
      return [model];
    case "deepseek":
      return [model, `deepseek/${model}`];
    // The model factory says `google`; the image reader's registry says `gemini` for the same API.
    case "google":
    case "gemini":
      return [`gemini/${model}`];
    case "openrouter":
      return [`openrouter/${model}`];
    default:
      return [];
  }
}

export function modelRates(provider: string, model: string): Entry | null {
  for (const key of tableKeys(provider, model)) {
    const hit = MODELS[key];
    if (hit) return hit;
  }
  return null;
}

// DeepSeek bills half price off-peak, and peak is 01:00-04:00 and 06:00-10:00 UTC on weekdays
// (api-docs.deepseek.com/quick_start/pricing, read 2026-09-25). The table carries the peak rates.
// Chinese public holidays are off-peak too and are not modelled, so a call on one is priced at the
// peak rate: an overstatement by the discount, never an understatement.
export function deepseekOffPeak(at: Date): boolean {
  const day = at.getUTCDay();
  if (day === 0 || day === 6) return true;
  const h = at.getUTCHours();
  return !((h >= 1 && h < 4) || (h >= 6 && h < 10));
}

export function callCostUsd(
  provider: string,
  model: string,
  tokens: PricedTokens,
  at: Date,
): number | null {
  const entry = modelRates(provider, model);
  if (!entry) return null;
  // The tier is chosen by the call's whole input, which is how the vendors state the threshold.
  const tier =
    entry.tiers
      ?.filter((t) => tokens.promptTokens > t.above)
      .sort((a, b) => b.above - a.above)[0] ?? entry;
  const read = tokens.cachedReadTokens;
  const write = tokens.cacheCreationTokens;
  if (read > 0 && tier.cachedInput === undefined) return null;
  if (write > 0 && tier.cacheWrite === undefined) return null;
  // Both cache counts are SUBSETS of the input (see `extractTokenUsage`), so the full rate applies
  // only to what is left of it.
  const fresh = Math.max(0, tokens.promptTokens - read - write);
  const perMillion =
    fresh * tier.input +
    read * (tier.cachedInput ?? 0) +
    write * (tier.cacheWrite ?? 0) +
    tokens.completionTokens * tier.output;
  const factor = provider === "deepseek" && deepseekOffPeak(at) ? 0.5 : 1;
  return (perMillion / 1e6) * factor;
}
