import table from "./model-prices.json";
import {
  findOverride,
  overridePriceTable,
  type PriceOverridesBlock,
} from "./overrides";
import { PRICE_TABLE_VERSION } from "./version";

// What one model call cost, in USD, priced when the ledger row is written from its own token counts,
// so a turn's cost is known when it ends (Langfuse's cost is asynchronous, paginated and rate
// limited). The table is LiteLLM's, regenerated by `scripts/refresh-model-prices.ts` and pinned
// (`PRICES_SOURCE`, `PRICES_READ_AT`); tests/modules/pricing.test.ts holds the provider defaults' rows
// to the vendors' pages. A call the table cannot price is `null`, never zero (a zero makes every total
// claim to be whole): an unknown model, `openai-compatible`, or a rate the row does not carry.

type Rates = {
  input: number;
  cachedInput?: number;
  cacheWrite?: number;
  // The 1-hour cache write. Absent on most rows, where it is derived (`cacheWrite1hRate`).
  cacheWrite1h?: number;
  output: number;
};
type Entry = Rates & { tiers?: (Rates & { above: number })[] };

const MODELS = table.models as Record<string, Entry>;

export const PRICES_SOURCE: string = table.source;
export const PRICES_READ_AT: string = table.readAt;

export interface PricedTokens {
  promptTokens: number;
  cachedReadTokens: number;
  cacheCreationTokens: number;
  // Of cacheCreationTokens, the 1-hour writes. Absent reads as none.
  cacheCreation1hTokens?: number;
  completionTokens: number;
}

// Where a provider's model lives in the table. The table is keyed the way LiteLLM routes, so the same
// model id means different rows for different providers: Google's AI Studio rows carry `gemini/`, and
// OpenRouter's carry `openrouter/` in front of the vendor-prefixed id OpenRouter itself uses.
// Exported for scripts/diff-model-prices.ts, which must find the defaults' rows the way the runtime does.
export function tableKeys(provider: string, model: string): string[] {
  switch (provider) {
    // A fine-tuned OpenAI id carries the organization and a suffix after the base
    // (`ft:gpt-4o-mini-2024-07-18:acme:support:abc123`), and the table lists the fine-tuning rates
    // under the base alone (`ft:gpt-4o-mini-2024-07-18`), since an organization's ids are never in it.
    case "openai":
      return model.startsWith("ft:") && model.split(":").length > 2
        ? [model, `ft:${model.split(":")[1]}`]
        : [model];
    case "anthropic":
      return [model];
    case "deepseek":
      return [model, `deepseek/${model}`];
    // The model factory says `google`; the image reader's registry says `gemini` for the same API.
    case "google":
    case "gemini":
      return [`gemini/${model}`];
    case "openrouter":
      return [`openrouter/${model}`];
    default:
      return [];
  }
}

// PROVIDERS LITELLM DOES NOT LIST, priced from the vendor's own page and pinned here with the date it
// was read, the way the table pins its commit. TypeSafe (the `decisions` engine's Jev) bills input
// tokens only, one price for every Jev version: docs.typesafe.ai/models, $0.042 per 1M input tokens,
// output free, read 2026-10-07.
const PUBLISHED_RATES: Readonly<Record<string, Entry>> = Object.freeze({
  typesafe: { input: 0.042, output: 0 },
});

export function modelRates(provider: string, model: string): Entry | null {
  const published = PUBLISHED_RATES[provider];
  if (published) return published;
  for (const key of tableKeys(provider, model)) {
    const hit = MODELS[key];
    if (hit) return hit;
  }
  return null;
}

// DeepSeek bills half price off-peak, and peak is 01:00-04:00 and 06:00-10:00 UTC on weekdays
// (api-docs.deepseek.com/quick_start/pricing, read 2026-09-25). The table carries the peak rates.
// Chinese public holidays are off-peak too and are not modelled, so a call on one is priced at the
// peak rate: an overstatement by the discount, never an understatement.
export function deepseekOffPeak(at: Date): boolean {
  const day = at.getUTCDay();
  if (day === 0 || day === 6) return true;
  const h = at.getUTCHours();
  return !((h >= 1 && h < 4) || (h >= 6 && h < 10));
}

export function callCostUsd(
  provider: string,
  model: string,
  tokens: PricedTokens,
  at: Date,
): number | null {
  const entry = modelRates(provider, model);
  if (!entry) return null;
  return costAt(entry, tokens, provider === "deepseek" && deepseekOffPeak(at));
}

// What priced the call, and at how much: the tenant's own price for this provider and model when it
// has one, the table otherwise. Recorded in `price_table`, so a wrong price can be corrected on exactly
// the rows it wrote. A tenant's price is taken as stated: no long-context tier, no DeepSeek off-peak.
export function priceCall(
  provider: string,
  model: string,
  tokens: PricedTokens,
  at: Date,
  overrides: PriceOverridesBlock | null,
): { costUsd: number | null; priceTable: string } {
  const own = overrides ? findOverride(overrides, provider, model) : null;
  if (own && overrides)
    return {
      // A cache rate the tenant left empty is "no discount": that part is charged at its input rate,
      // since a price the account stated must not turn a call into no price at all.
      costUsd: costAt(
        {
          ...own,
          cachedInput: own.cachedInput ?? own.input,
          cacheWrite: own.cacheWrite ?? own.input,
          cacheWrite1h: 2 * own.input,
        },
        tokens,
        false,
      ),
      priceTable: overridePriceTable(overrides),
    };
  return {
    costUsd: callCostUsd(provider, model, tokens, at),
    priceTable: PRICE_TABLE_VERSION,
  };
}

// Anthropic bills a 1-hour cache write at 2x the base input rate on every model
// (Anthropic prompt-caching pricing: a 1-hour write is 2x base input), and the table carries the rate on
// few rows, so a row without it is priced from its input. A row with no cache-write rate at all is a
// model that does not write a cache, and a 1-hour write there has no price.
function cacheWrite1hRate(tier: Rates): number | undefined {
  if (tier.cacheWrite1h !== undefined) return tier.cacheWrite1h;
  return tier.cacheWrite === undefined ? undefined : 2 * tier.input;
}

// Exported for the tests, which price rows the table does not carry yet (a stated 1-hour rate).
export function costAt(
  entry: Entry,
  tokens: PricedTokens,
  halfPrice: boolean,
): number | null {
  // The tier is chosen by the call's whole input, which is how the vendors state the threshold.
  const tier =
    entry.tiers
      ?.filter((t) => tokens.promptTokens > t.above)
      .sort((a, b) => b.above - a.above)[0] ?? entry;
  const read = tokens.cachedReadTokens;
  const write = tokens.cacheCreationTokens;
  // The 1-hour writes are a subset of the writes, priced at their own rate; the rest are 5-minute ones.
  const write1h = Math.min(write, tokens.cacheCreation1hTokens ?? 0);
  const write5m = write - write1h;
  const rate1h = cacheWrite1hRate(tier);
  if (read > 0 && tier.cachedInput === undefined) return null;
  if (write5m > 0 && tier.cacheWrite === undefined) return null;
  if (write1h > 0 && rate1h === undefined) return null;
  // Both cache counts are SUBSETS of the input (see `extractTokenUsage`), so the full rate applies
  // only to what is left of it.
  const fresh = Math.max(0, tokens.promptTokens - read - write);
  const perMillion =
    fresh * tier.input +
    read * (tier.cachedInput ?? 0) +
    write5m * (tier.cacheWrite ?? 0) +
    write1h * (rate1h ?? 0) +
    tokens.completionTokens * tier.output;
  return (perMillion / 1e6) * (halfPrice ? 0.5 : 1);
}
