// Generated by scripts/refresh-model-prices.ts with model-prices.json. Do not edit by hand.
export const PRICE_TABLE_READ_AT = "2026-10-05";
export const PRICE_TABLE_VERSION = "litellm@29b4f20572d5";
