// Generated by scripts/refresh-model-prices.ts with model-prices.json. Do not edit by hand.
export const PRICE_TABLE_READ_AT = "2026-09-25";
export const PRICE_TABLE_VERSION = "litellm@e106dbd8ba9b";
