-- Superseded by `20260904170000_audit_keyset_by_time`. ONE DROP PER FILE, and that is measured, not
-- style: two `DROP INDEX CONCURRENTLY` statements in one migration are sent as a multi-command
-- message, which Postgres runs as an implicit transaction, and the command refuses one --
-- `DROP INDEX CONCURRENTLY cannot run inside a transaction block`. (Several `CREATE INDEX
-- CONCURRENTLY` in one file do NOT hit this, which is why the migration before this one holds three.)
--
-- CONCURRENTLY at all because a plain `DROP INDEX` takes ACCESS EXCLUSIVE on the TABLE rather than on
-- the index: it waits behind any audit read in flight, and every audited mutation queues behind it --
-- the exact blocking the concurrent builds exist to avoid.
--
-- Replaced by NOTHING. It served the fleet trail's first page back when pages were ordered by `id`; every read moved onto `(created_at, id)`, so no query reaches for it and it was pure write cost on a table every audited mutation writes to.
DROP INDEX CONCURRENTLY IF EXISTS "audit_logs_fleet_id_idx";
