#!/usr/bin/env bun
// Regenerates src/modules/pricing/model-prices.json from LiteLLM's price table (MIT), pinned to the
// commit it was read at. Run by hand when a provider changes its prices or a model the operators use
// comes up "no price"; the diff is the review. Nothing reads the network at runtime.
//
//   bun scripts/refresh-model-prices.ts
//
// Only the chat models of the providers the model factory speaks to are kept, and only the four
// rates a ledger row can use, in USD per MILLION tokens so a reviewer can hold them against the
// vendor's page. A rate above a context threshold (OpenAI's >272K, Gemini's >200K) is kept as a tier.

const REPO = "BerriAI/litellm";
const FILE = "model_prices_and_context_window.json";
const OUT = "src/modules/pricing/model-prices.json";
// The table's identity on its own, import-free, so the console can name the table without shipping it.
const VERSION_OUT = "src/modules/pricing/version.ts";

// LiteLLM's provider name → ours.
const PROVIDERS: Record<string, string> = {
  openai: "openai",
  anthropic: "anthropic",
  gemini: "google",
  deepseek: "deepseek",
  openrouter: "openrouter",
};

type Rates = {
  input: number;
  cachedInput?: number;
  cacheWrite?: number;
  output: number;
};
type Entry = Rates & { tiers?: (Rates & { above: number })[] };

const perMillion = (v: unknown): number | undefined =>
  typeof v === "number" && Number.isFinite(v)
    ? Math.round(v * 1e6 * 1e6) / 1e6
    : undefined;

function rates(e: Record<string, unknown>, suffix: string): Rates | null {
  const input = perMillion(e[`input_cost_per_token${suffix}`]);
  const output = perMillion(e[`output_cost_per_token${suffix}`]);
  if (input === undefined || output === undefined) return null;
  const r: Rates = { input, output };
  const cachedInput = perMillion(e[`cache_read_input_token_cost${suffix}`]);
  const cacheWrite = perMillion(e[`cache_creation_input_token_cost${suffix}`]);
  if (cachedInput !== undefined) r.cachedInput = cachedInput;
  if (cacheWrite !== undefined) r.cacheWrite = cacheWrite;
  return r;
}

const commit = (await (
  await fetch(
    `https://api.github.com/repos/${REPO}/commits?path=${FILE}&per_page=1`,
  )
).json()) as { sha: string; commit: { committer: { date: string } } }[];
const sha = commit[0]?.sha;
if (!sha) throw new Error("could not resolve the LiteLLM commit");
const table = (await (
  await fetch(`https://raw.githubusercontent.com/${REPO}/${sha}/${FILE}`)
).json()) as Record<string, Record<string, unknown>>;

const models: Record<string, Entry> = {};
for (const [key, e] of Object.entries(table)) {
  if (typeof e !== "object" || e === null) continue;
  if (e.mode !== "chat" && e.mode !== "responses") continue;
  if (
    typeof e.litellm_provider !== "string" ||
    !(e.litellm_provider in PROVIDERS)
  )
    continue;
  const base = rates(e, "");
  if (!base) continue;
  const thresholds = new Set<number>();
  for (const k of Object.keys(e)) {
    const m = /^input_cost_per_token_above_(\d+)k_tokens$/.exec(k);
    if (m) thresholds.add(Number(m[1]) * 1000);
  }
  const tiers = [...thresholds]
    .sort((a, b) => a - b)
    .flatMap((above) => {
      const r = rates(e, `_above_${above / 1000}k_tokens`);
      return r ? [{ above, ...r }] : [];
    });
  models[key] = tiers.length > 0 ? { ...base, tiers } : base;
}

const readAt = new Date().toISOString().slice(0, 10);
const sorted = Object.fromEntries(
  Object.entries(models).sort(([a], [b]) => a.localeCompare(b)),
);
await Bun.write(
  OUT,
  `${JSON.stringify(
    {
      source: `https://github.com/${REPO}/blob/${sha}/${FILE}`,
      readAt,
      models: sorted,
    },
    null,
    2,
  )}\n`,
);
await Bun.write(
  VERSION_OUT,
  `// Generated by scripts/refresh-model-prices.ts with model-prices.json. Do not edit by hand.
export const PRICE_TABLE_READ_AT = "${readAt}";
export const PRICE_TABLE_VERSION = "litellm@${sha.slice(0, 12)}";
`,
);
console.log(
  `${Object.keys(sorted).length} models from ${REPO}@${sha.slice(0, 12)} → ${OUT}`,
);
