import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@/../generated/prisma/client";
import { contactInboxThreadId } from "@/graph/checkpointer";
import { clearTurnOwning, markTurnOwning } from "@/graph/thread-claim";
const tenantId = BigInt(process.env.V_TENANT as string);
const instanceId = BigInt(process.env.V_INSTANCE as string);
const contactInboxId = Number(process.env.V_CONTACT_INBOX as string);
const appDb = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.TEST_APP_DATABASE_URL as string }) });
const suDb = new PrismaClient({ adapter: new PrismaPg({ connectionString: process.env.MIGRATION_DATABASE_URL as string }) });
const owner = { tenantId, instanceId, contactInboxId, graphThreadId: contactInboxThreadId(tenantId, instanceId, contactInboxId) };
const read = async () => (await suDb.$queryRaw<{turn_holders:number;turn_held_until:Date|null}[]>`SELECT turn_holders, turn_held_until FROM agent_threads WHERE tenant_id=${tenantId} AND contact_inbox_id=${contactInboxId}`)[0];
console.log("before", JSON.stringify(await read()));
const h = await markTurnOwning(owner, appDb);
console.log("hold", h.epoch, "heldBefore", h.heldBefore);
console.log("after-bump", JSON.stringify(await read()));
await clearTurnOwning(owner, appDb, h);
console.log("after-clear", JSON.stringify(await read()));
process.exit(0);
